services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag_network_backend
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONGODB_DATABASE: mini_rag
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - rag_network_backend
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  rag_network_backend:
    driver: bridge

volumes:
  mongodb_data:
  pgvector_data:
