APP_NAME=mini-RAG
APP_VERSION=0.1
FILE_ALLOWED_TYPES=["text/plain", "application/pdf"]
FILE_MAX_SIZE=10
FILE_CHUNK_SIZE=1000

# LLM API Keys
OPENAI_API_KEY=
COHERE_API_KEY=your_cohere_key_here
GOOGLE_API_KEY=your_google_key_here
OLLAMA_BASE_URL=http://host.docker.internal:11434/v1/

OPENAI_API_URL=

# ==Backends==
GENERATION_BACKEND_LLM_LITERAL=["OPENAI","OLLAMA","COHERE","GOOGLE"]
GENERATION_BACKEND_LLM=COHERE

EMBEDDING_BACKEND_LLM_LITERAL=["COHERE","OLLAMA","GOOGLE","OPENAI"]
EMBEDDING_BACKEND_LLM=COHERE

# ==Models==
GENERATION_MODEL_ID=command-r-plus
EMBEDDING_MODEL_ID=embed-multilingual-v3.0
EMBEDDING_MODEL_SIZE=1024

INPUT_MAX_CHARACTERS=1024
GENERATION_MAX_OUTPUT_TOKENS=512
GENERATION_TEMPERATURE=0.1

# ===================Database==========================
DATABASE_TYPE=SQL
DATABASE_TYPE_LITERAL=["NOSQL","SQL"]

# NoSQL (MongoDB)
MONGODB_URL=mongodb://mongodb:27017
MONGODB_DB=mini_rag

# SQL (Postgres)
POSTGRES_USERNAME=minirag
POSTGRES_PASSWORD=minirag
POSTGRES_HOST=pgvector
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE=mini_rag

# ===================Vector DB====================
VECTOR_DB_BACKEND=PGVECTOR
VECTOR_DB_BACKEND_LITERAL=["QDRANT","PGVECTOR"]
VECTOR_DB_DISTANCE_METHOD=COSINE

VECTOR_QDRANT_DB_PATH=qdrant_db
VECTOR_POSTGRES_DB_URL=postgresql://minirag:minirag@pgvector:5432/mini_rag
VECTOR_POSTGRES_INDEX_CREATION_THRESHOLD=100

# ===================Template Config====================
DEFAULT_LANG=ar
